/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eorhcjduyidgudehvgar"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcmhjamR1eWlkZ3VkZWh2Z2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDUwOTgsImV4cCI6MjA4OTUyMTA5OH0.kZ3lW1BCSpOQ-Cuux2hHqi0UJ0-WoNh60tVzG7jApjY"